# Generated by Django 3.1.1 on 2020-09-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('sub_tittle', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
